name: Build ADMX Viewer

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: |
            ${{ runner.os }}-playwright

      - name: Install dependencies and Playwright
        run: |
          pip install -r scripts/requirements.txt
          playwright install --with-deps

      - name: Scrape ZIP URLs with Playwright (with fallback)
        run: python scripts/scrape_admx_zips.py

      - name: Debug ZIP URLs
        run: |
          echo "Contents of zip_urls.txt:"
          cat zip_urls.txt || echo "❌ zip_urls.txt not found!"

      - name: Download ADMX ZIPs
        run: |
          mkdir -p zips
          while IFS= read -r url; do
            fname=$(basename "$url")
            echo "📥 Downloading $fname"
            curl -L --fail "$url" -o "zips/$fname" || echo "❌ Failed: $fname"
          done < zip_urls.txt

      - name: Debug downloaded files
        run: file zips/* || echo "No zip files"

      - name: Extract PolicyDefinitions from ZIPs
        run: |
          mkdir -p tmp admxfiles
          for zip in zips/*.zip; do
            unzip -o "$zip" -d tmp || echo "❌ Failed to unzip $zip"
          done
          find tmp -type d -name PolicyDefinitions -exec cp -r {}/* admxfiles/ \; || echo "❌ No PolicyDefinitions found"

      - name: Parse ADMX files to JSON
        run: |
          mkdir -p public
          python scripts/parse_admx.py admxfiles/ public/

      - name: Debug public output
        run: ls -R public || echo "❌ Nothing in public"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
