name: Build ADMX Viewer

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
          playwright install --with-deps

      - name: Scrape ZIP URLs with Playwright
        run: python scripts/scrape_admx_zips.py

      - name: Download ADMX ZIPs
        run: |
          mkdir zips
          while IFS= read -r url; do
            fname=$(basename "$url")
            echo "Downloading $fname"
            curl -L "$url" -o "zips/$fname"
          done < zip_urls.txt

      - name: Extract PolicyDefinitions from ZIPs
        run: |
          mkdir admxfiles
          for zip in zips/*.zip; do
            unzip -o "$zip" -d tmp
          done
          find tmp -type d -name PolicyDefinitions -exec cp -r {}/* admxfiles/ \;

      - name: Run ADMX Parser
        run: python scripts/parse_admx.py admxfiles/ public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
